server:
  port: 7002
spring:
  application:
    name: cloud-consumer-order-nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
service-url:
  nacos-user-service: http://cloud-provider-payment-nacos
feign:
  sentinel:
    enabled: true